version: "3.4"
services:
  netbox:
    ports:
      - "8000:8080"
    environment:
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: "example-token"
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
  bulk-loagen:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../config.yaml:/config.yaml
    environment:
      NETBOX_HOST: "netbox:8080"
      NETBOX_SCHEME: "http"
      NETBOX_TOKEN: "example-token"
